auth:
    path:     /v1/auth
    defaults: { _controller: TensideCoreBundle:Auth:checkAuth }
    methods:  [GET, POST]

composer_json_get:
    path:     /v1/composer.json
    defaults: { _controller: TensideCoreBundle:ComposerJson:getComposerJson }
    methods:  [GET]
    options:
        required_role: ROLE_EDIT_COMPOSER_JSON

composer_json_put:
    path:     /v1/composer.json
    defaults: { _controller: TensideCoreBundle:ComposerJson:putComposerJson }
    methods:  [PUT]
    options:
        required_role: ROLE_EDIT_COMPOSER_JSON

app_kernel_get:
    path:     /v1/AppKernel.php
    defaults: { _controller: TensideCoreBundle:AppKernel:getAppKernel }
    methods:  [GET]
    options:
        required_role: ROLE_EDIT_APP_KERNEL

app_kernel_put:
    path:     /v1/AppKernel.php
    defaults: { _controller: TensideCoreBundle:AppKernel:putAppKernel }
    methods:  [PUT]
    options:
        required_role: ROLE_EDIT_APP_KERNEL

packages_get:
    path:     /v1/packages
    defaults: { _controller: TensideCoreBundle:Package:packageList }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

package_get:
    path:     /v1/packages/{vendor}/{package}
    defaults: { _controller: TensideCoreBundle:Package:getPackage }
    methods:  [GET]
    requirements:
        vendor: "[\\-\\_a-zA-Z0-9]+"
        package: "[\\-\\_a-zA-Z0-9]+"
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

package_put:
    path:     /v1/packages/{vendor}/{package}
    defaults: { _controller: TensideCoreBundle:Package:putPackage }
    methods:  [PUT]
    requirements:
        vendor: "[\\-\\_a-zA-Z0-9]+"
        package: "[\\-\\_a-zA-Z0-9]+"
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

search_package_put:
    path:     /v1/search
    defaults: { _controller: TensideCoreBundle:SearchPackage:search }
    methods:  [PUT]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

tasks_run:
    path:     /v1/tasks/run
    defaults: { _controller: TensideCoreBundle:TaskRunner:run }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

task_get:
    path:     /v1/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTask }
    methods:  [GET]
    requirements:
        taskId: "[a-z0-9]+"
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

tasks_get:
    path:     /v1/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:getTasks }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

task_add:
    path:     /v1/tasks
    defaults: { _controller: TensideCoreBundle:TaskRunner:addTask }
    methods:  [POST]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

task_delete:
    path:     /v1/tasks/{taskId}
    defaults: { _controller: TensideCoreBundle:TaskRunner:deleteTask }
    methods:  [DELETE]
    requirements:
        taskId: "[a-z0-9]+"
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

install_configure:
    path:     /v1/install/configure
    defaults: { _controller: TensideCoreBundle:InstallProject:configure }
    methods:  [POST]

install_create_project:
    path:     /v1/install/create-project
    defaults: { _controller: TensideCoreBundle:InstallProject:createProject }
    methods:  [POST]

install_selftest:
    path:     /v1/install/selftest
    defaults: { _controller: TensideCoreBundle:InstallProject:getSelfTest }
    methods:  [GET]

install_autoconfig:
    path:     /v1/install/autoconfig
    defaults: { _controller: TensideCoreBundle:InstallProject:getAutoConfig }
    methods:  [GET]

install_search_project:
    path:     /v1/install/search-project/{vendor}/{project}
    defaults: { _controller: TensideCoreBundle:InstallProject:getProjectVersions }
    methods:  [GET]
    requirements:
        vendor: "[\\-\\_a-zA-Z0-9]+"
        project: "[\\-\\_a-zA-Z0-9]+"

install_get_state:
    path:     /v1/install/get_state
    defaults: { _controller: TensideCoreBundle:InstallProject:getInstallationState }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

selftest_alltests:
    path:     /v1/selftest
    defaults: { _controller: TensideCoreBundle:SelfTest:getAllTests }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS

selftest_autoconfig:
    path:     /v1/autoconfig
    defaults: { _controller: TensideCoreBundle:SelfTest:getAutoConfig }
    methods:  [GET]
    options:
        required_role: ROLE_MANIPULATE_REQUIREMENTS
