services:
    tenside:
        class:         Tenside\Tenside
        arguments:     ["@tenside.home"]

    tenside.home:
        class:  Tenside\CoreBundle\HomePathDeterminator
        public: true

    tenside.cli_script:
        class:     Tenside\CoreBundle\CliScriptDeterminator
        # I really hope this works out as intended, if not inject the kernel.
        arguments: ["%kernel.root_dir%/%tenside.script_name%"]
        public:    true

    tenside.config:
        class:          Tenside\CoreBundle\TensideJsonConfig
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\TensideJsonConfigFactory
        factory_method: create
        arguments:      ["@tenside.home"]
        public:         true

    tenside.tasks:
        class:          Tenside\Task\TaskList
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\TaskListFactory
        factory_method: create
        arguments:      ["@tenside.home", "@event_dispatcher"]
        public:         true

    tenside.composer_json:
        class:          Tenside\Composer\ComposerJson
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\ComposerJsonFactory
        factory_method: create
        arguments:      ["@tenside.home"]
        shared:         false

    tenside.user_provider:
        class:     Tenside\CoreBundle\Security\UserProviderFromConfig
        arguments: ["@tenside.config"]

    tenside.exception_renderer:
        class: Tenside\CoreBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    tenside.task_listener:
        class: Tenside\CoreBundle\EventListener\TaskListener
        tags:
            - { name: kernel.event_listener, event: tenside.create_task, method: onCreateTask }

    tenside.jwt_authenticator:
        class:     Tenside\CoreBundle\Security\JWTAuthenticator
        arguments: ["@tenside.config"]
        public:    true

    tenside.permission_voter:
        class:     Tenside\CoreBundle\Security\PermissionVoter
        arguments: ["@router", "@request_stack"]
        tags:
            - { name: security.voter }
        public:    false

    tenside.logger:
        class:          Monolog\Handler\RotatingFileHandler
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\Loggerfactory
        factory_method: create
        arguments:     ["@kernel", "%kernel.environment%.log", 10, 'info']
