services:
    tenside.home:
        class:  Tenside\CoreBundle\HomePathDeterminator
        public: true

    tenside.status:
        class:     Tenside\CoreBundle\InstallationStatusDeterminator
        arguments: ["@tenside.home"]
        public: true

    tenside.cli_script:
        class:     Tenside\CoreBundle\CliScriptDeterminator
        # I really hope this works out as intended, if not inject the kernel.
        arguments: ["%kernel.root_dir%/%tenside.script_name%"]
        public:    true

    tenside.config:
        class:          Tenside\CoreBundle\TensideJsonConfig
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\TensideJsonConfigFactory
        factory_method: create
        arguments:      ["@tenside.home"]
        public:         true

    tenside.tasks:
        class:          Tenside\Task\TaskList
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\TaskListFactory
        factory_method: create
        arguments:      ["@tenside.home", "@event_dispatcher"]
        public:         true

    tenside.composer_json:
        class:          Tenside\Composer\ComposerJson
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\ComposerJsonFactory
        factory_method: create
        arguments:      ["@tenside.home"]
        shared:         false

    tenside.taskrun_lock:
        class:          Symfony\Component\Filesystem\LockHandler
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\TaskRunLockHandlerFactory
        factory_method: create
        arguments:      ["@tenside.home"]

    tenside.user_provider:
        class:     Tenside\CoreBundle\Security\UserProviderFromConfig
        arguments: ["@tenside.config"]

    tenside.exception_renderer:
        class:     Tenside\CoreBundle\EventListener\ExceptionListener
        arguments:
          logger:  "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    tenside.task_listener:
        class:     Tenside\CoreBundle\EventListener\TaskListener
        arguments: ["@tenside.home"]
        tags:
            - { name: kernel.event_listener, event: tenside.create_task, method: onCreateTask }

    tenside.jwt_authenticator:
        class:     Tenside\CoreBundle\Security\JWTAuthenticator
        arguments: ["@tenside.config"]
        public:    true
        # cannot be shared as the install controller is manipulating the secret.
        shared:    false

    tenside.permission_voter:
        class:     Tenside\CoreBundle\Security\PermissionVoter
        arguments: ["@router", "@request_stack"]
        tags:
            - { name: security.voter }
        public:    false

    tenside.logger:
        class:          Monolog\Handler\RotatingFileHandler
        factory_class:  Tenside\CoreBundle\DependencyInjection\Factory\LoggerFactory
        factory_method: create
        arguments:     ["@kernel", "%kernel.environment%.log", 10, 'debug']

    tenside.apidoc_parser:
        class:          Tenside\CoreBundle\TensideApiDocHandler
        tags:
          - { name: nelmio_api_doc.extractor.handler }
        public: false
