platform: x86
clone_folder: c:\projects\tenside-core

cache:
  - '%LOCALAPPDATA%\Composer\files'

environment:
  matrix:
    # Keep older versions last so we always have current results first.
    - php_zip: php-7.1.0-Win32-VC14-x86.zip
    - php_zip: php-7.0.13-Win32-VC14-x86.zip
    - php_zip: php-5.6.28-Win32-VC11-x86.zip

init:
  - SET PATH=c:\php;%PATH%
  - SET SYMFONY_DEPRECATIONS_HELPER=weak

install:
  - mkdir c:\php && cd c:\php
  - ps: appveyor DownloadFile http://windows.php.net/downloads/releases/archives/$env:php_zip
  - ps: 7z x $env:php_zip -y >$null
  - del *.zip
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_bz2.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - cd c:\projects\tenside-core
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

build: off

test_script:
  - cd c:\projects\tenside-core
  - vendor\bin\phpunit.bat
